<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBlogPostTable extends Doctrine_Table
{
  public function retrieveLatestPosts($num)
  {
    $q = Doctrine::getTable('Content')
      ->getTypeQuery('BlogPost')
      ->orderBy('c.date_published DESC')
      ->limit($num);

    return $q->execute();
  }

  public function retrieveTopAuthors($num)
  {
    $userTable = Doctrine::getTable('User');
    $q = $userTable
      ->createQuery('u')
      ->select('*, count(uc.id) as num_posts')
      ->innerJoin('u.CreatedContent uc')
      ->innerJoin('uc.Type t WITH t.name = ?', 'BlogPost')
      ->groupBy(implode(', ', $userTable->getFieldNames())) 
      ->limit($num);

    return $q->execute();
  }

  public function retrieveMonths()
  {
    $results = Doctrine_Core::getTable('Content')
      ->getTypeQuery('BlogPost')
      ->select('c.date_published')
      ->where('c.is_published = 1')
      ->orderBy('c.date_published DESC')
      ->execute(array(), Doctrine_Core::HYDRATE_NONE);
    $months = array();
    foreach ($results as $result)
    {
      $months[] = date('m/1/Y', strtotime($result[0]));
    }
    $months = array_unique($months);
    return $months;
  }

  public function retrieveBlogMonth($month, $year)
  {
    $start = date('Y-m-d', strtotime($month.'/01/'.$year));
    $end = date('Y-m-d', strtotime($start.' +1 month'));
    $end = date('Y-m-d', strtotime($end.' -1 day'));
    $dates = array($start, $end);

    Doctrine::getTable('BlogPost');

    $q = Doctrine::getTable('Content')
      ->createQuery('e')
      ->innerJoin('e.BlogPost p')
      ->innerJoin('e.Type t2')
      ->where('e.date_published > ? AND e.date_published < ?', $dates);
    
    $pager = new sfDoctrinePager('Content', sfSympalConfig::get('rows_per_page'));
    $pager->setQuery($q);
    $pager->init();

    return $pager;
  }
}