all:
  sympal_config:
    sfSympalBlogPost:
      enable_comments: true
      content_templates:
        default_view:
          template: sympal_blog/view
    sfSympalContentList:
      content_templates:
        blog_post_list:
          template: sympal_blog/list