all:
  sympal_config:
    blog-post:
      enable_comments: true
      content_templates:
        default_view:
          template: sympal_blog/view
    content-list:
      content_templates:
        blog_post_list:
          template: sympal_blog/list