all:
  sympal_config:
    internationalized_models:
      sfSympalBlogPost: [title, teaser]
    blog:
      post_history: 20
      sidebar:
        # The widgets (and the order) that will be displayed. Defaults to ALL widgets
        display: [toc, latest_posts, monthly_history]
        widgets:
          latest_posts: sympal_blog/latest_posts
          monthly_history: sympal_blog/monthly_history
          toc: sympal_blog/toc
          #my_sidebar_widget: template: my_module/sidebar
    content_types:
      sfSympalBlogPost:
        content_templates:
          default_view:
            template: sympal_blog/view
          view_with_comments:
            template: sympal_blog/view_with_comments
        content_slots:
          title:
            type:      Text
            edit_mode: inline
          body:
            type:      Markdown
            edit_mode: inline
      sfSympalContentList:
        content_templates:
          blog_post_list:
            template: sympal_blog/list
    sfSympalBlogPlugin:
      enable_comments: true
